### ISSUE TITLE
[Documentation] add comments to examples 

### ISSUE THREAD

**Issue by xnacly** [Flam3rboy/missing-native-js-functions#12]
Please add a comment for each console.log in the examples dir, so i can make the docs more easily

~ thanks

**Comment by samuelscheit** [comment]
yes

**Comment by samuelscheit** [comment]
done in [fd45d9f4377a](https://github.com/Flam3rboy/missing-native-JS-functions/compare/ba2af2ee200a...fd45d9f4377a)
